name: adams_clock
description: A Clock that looks like space.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_clock_helper: 
    path: ../flutter_clock_helper
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
   - assets/stars.png
   - assets/moon.png
   - assets/sun_1.png
   - assets/sun_2.png
   - assets/sun_3.png
   - assets/sun_4.png
   - assets/earth.png
   - assets/shadow.png

  fonts:
    - family: NovaMono
      fonts:
        - asset: assets/NovaMono-Regular.ttf        
          weight: 700